In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])


In [4]:
arr=a1+a2
arr

array([ 7,  9, 11, 13, 15])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [7]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [9]:
l=[10,20,30,40]
arr=np.array(l)


In [11]:
arr+10

array([20, 30, 40, 50])

In [14]:
a=np.arange(1,21)
slice=a[:5]
slice +10

array([11, 12, 13, 14, 15])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
m1=np.array([[1,2],[3,4]])


In [24]:
m2=np.array([[5,6],[7,8]])

In [25]:
m1*m2

array([[ 5, 12],
       [21, 32]])

In [26]:
m1@m2

array([[19, 22],
       [43, 50]])

In [27]:
np.dot(m1,m2)

array([[19, 22],
       [43, 50]])

In [28]:
m1.transpose()

array([[1, 3],
       [2, 4]])

In [29]:
m1.T

array([[1, 3],
       [2, 4]])

In [30]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [31]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [32]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [34]:
a=np.arange(1,21).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [36]:
np.hsplit(a,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [40]:
np.vsplit(a,5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]