In [9]:
print("hello")

hello


In [10]:
print("How are Your")

How are Your


In [11]:
def hello():
    print("How are You")

In [12]:
hello()

How are You


In [13]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [14]:
import numpy as np

In [15]:
arr=np.array([1,2,3,4,5])

In [16]:
arr

array([1, 2, 3, 4, 5])

In [18]:
a=[1,2,3,4,"Hello"]
a

[1, 2, 3, 4, 'Hello']

In [19]:
np.array(a)

array(['1', '2', '3', '4', 'Hello'], dtype='<U21')

In [20]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [21]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
a=np.arange(1,11) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
a=np.arange(1,11,2) 
a

array([1, 3, 5, 7, 9])

In [28]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [29]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [30]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
np.random.rand(10)


array([4.76054660e-01, 6.26830175e-01, 3.04794949e-01, 4.71920128e-01,
       1.66307833e-01, 3.52799392e-02, 9.83023068e-01, 7.21812170e-01,
       3.61630564e-01, 6.58792843e-04])

In [34]:
np.random.randn(10)

array([ 0.06353462,  1.79269425, -1.07720497, -0.8686813 , -0.54244781,
        1.36793691, -0.55074532, -0.94841668, -1.55774418, -0.7180184 ])

In [36]:
np.random.randint(10,20,5)

array([14, 15, 11, 19, 13])

In [37]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.dtype


dtype('int64')

In [39]:
arr.shape

(3, 3)

In [40]:
arr.size

9

In [41]:
arr.min()

np.int64(1)

In [42]:
arr.max()

np.int64(9)

In [43]:
arr.sum()

np.int64(45)

In [44]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [45]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [46]:
arr.mean()

np.float64(5.0)

In [47]:
arr.std()

np.float64(2.581988897471611)

In [48]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
arr.reshape(6,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])