In [2]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[0]

np.int64(11)

In [6]:
arr[1:4]

array([12, 13, 14])

In [7]:
arr[:4]

array([11, 12, 13, 14])

In [8]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[1::2]

array([12, 14, 16, 18, 20])

In [11]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [13]:
arr[0,0]

np.int64(1)

In [15]:
arr[0][0]

np.int64(1)

In [16]:
arr[0:2,1:3]

array([[2, 3],
       [8, 9]])

In [21]:
arr[3:,3:]

array([[22, 23, 24],
       [28, 29, 30]])

In [22]:
arr=np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr%2==0
bool_index

array([ True,  True,  True,  True,  True,  True])

In [30]:
arr=arr[bool_index]
arr

array([10, 12, 14, 16, 18, 20])